# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Grant permissions to read contents and deploy pages
permissions:
  contents: read
  pages: write
  id-token: write

# Configure deployment environment
pages:
  build:
    runs-on: ubuntu-latest
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install and Build with Astro
        # This step handles:
        # 1. Installing Node.js
        # 2. Installing dependencies (npm install, yarn, or pnpm)
        # 3. Running the build command (npm run build)
        # 4. Uploading the 'dist' (or 'out') directory as the 'github-pages' artifact
        uses: withastro/action@v3

  deploy:
    # Runs only after the build job is successful
    needs: build 
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # This action automatically downloads and deploys the 'github-pages' artifact
        uses: actions/deploy-pages@v4